version: '3.8'

services:
  selenium-tests:
    build: .
    container_name: selenium-test-runner
    environment:
      - HEADLESS=true
      - BROWSER=chrome
      - DISPLAY=:99
    volumes:
      # 테스트 결과를 호스트에 마운트
      - ./reports:/app/reports
      # 로그 파일 마운트
      - ./logs:/app/logs
    networks:
      - selenium-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import selenium; print('Selenium is working')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 선택적: 테스트 결과를 웹으로 확인할 수 있는 서비스
  nginx:
    image: nginx:alpine
    container_name: selenium-reports
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - selenium-tests
    networks:
      - selenium-network
    restart: unless-stopped
    profiles:
      - web

networks:
  selenium-network:
    driver: bridge

volumes:
  test-reports:
    driver: local
